name: AstroCore
version: 1.0
main: dev.malvaito.AstroCore
author: Malvaito
api-version: 1.21
dependencies:
  - PlaceholderAPI
commands:
  randomchest:
  eco:
  balance:
  pay:
  msg:
  r:
  tpa:
  tpahere:
  tpaccept:
  tpadeny:
  tab:
  setspawn:
  spawn:
  feed: